apiVersion: apps/v1
kind: Deployment
metadata:
    name: accounts-deployment
    labels:
      app: accounts
spec:
  replicas: 1
  template:
    metadata: 
      labels:
       app: accounts
    spec:
      containers:
      - name: accounts
        image: emaaddocker/accounts:latest
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: accounts
             
---

apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
 selector:
    app: accounts
 type: LoadBalancer
 ports:
     - protocol: TCP
       port: 8080
       targetPort: 8080
            
      

