{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.deploymentName }}
 labels:
   app: {{ .Values.deploymentLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels: 
        app: {{ .Values.deploymentLabel }}
    spec:
       containers:
         - name: {{ .Values.deploymentLabel }}
           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
           ports:
           - containerPort: {{ .Values.containerPort }}
             protocol: TCP
  selector:
   matchLabels:
    app: {{ .Values.deploymentLabel }}

{{- end -}}